import React, { Component } from 'react'
import './About.css'

export default class About extends Component {
    render() {
        return (
            <div className="aboutPage">
                <div className="about">
                    <h1>About My Seed 3 project</h1>
                    <ul>
                        <li>Generated by React.</li>
                        <li>Uses an Express server.</li>
                        <li>Uses a MongoDB database with Mongoose.</li>
                        <li>Allows the creation and deletion of books and there reviews.</li>
                        <li>Is composed of several components.</li>
                    </ul>
                </div>

                <div className="creater">
                    <h3>Created By: Justin Myers <i><b>a.k.a</b> Jelly Bean</i></h3>
                </div>
            </div>
        )
    }
}